[firebase]
  apiKey="AIzaSyATgetk0rvly--sN-wF_MlqUUCuj0iiyY8"
  authDomain="ai-tax-advisor-70984.firebaseapp.com"
  projectId=ai-tax-advisor-70984"
  storageBucket="ai-tax-advisor-70984.firebasestorage.app"
  messagingSenderId="266778354857"
  appId="1:266778354857:web:fd4f278d7dce90a6f8f5b8"


 [firebase_service_account]
  type="service_account"
  project_id="ai-tax-advisor-70984"
  private_key_id="8145ddd3291e600e69c8bb04a8be3f95578e1606"
  private_key="""-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDp/ychKMPyHSEH\nvDcwgB81EkhHxcQnzjn0SL2SSUXR6+w5hDk5viZaC05EilHotBAmIqqIzxVYE/pn\n3s7iERF9oFUrLJFGwHdsdoWBIX/pRVs4w6jstZyRsbCCe6lwq3ISxnM3ZJZ4kuqe\nRIi1RaMPb+eORMuxuT9oaIrdOSwvlMKkZ/eklgD12lnRghnB6/nUAtVxr4j63qan\nV3G5wmGhT5fdexYUL6Y5JmZvDU/ynHTHOTvnVHgSxSDtL8I/fnU6eX8m3cv69iT3\nEVyMih5k+aGhcTz+e56fnVfxNq26xnPsWH4QUQRyX6DOWjGomVfa6wEp4gHdibWS\n7X4er87nAgMBAAECggEAI3GhtLUfESJ2aVyKI4+Uqo5NYonDT6A+SRFnnav5pnWM\n/51WqbdyybrirSEijRQRSiWAHV74xbGpAWjPf5DETHonzHVgwA3RSR2e1VOEs4ns\n6mlAwjI0OCFpMiqXHNjrW4qx0xcqb7MZVMXey050B5eUxIkJLa94ulDzj9TkK4Sb\n2z1RHF4oxbwxHfYjxUmEPWXHcqyGRcmP8Ib0OfhzIqSrwf+UdYP37lAN9oBnTTD9\nQ1RbO/DXWxiSbkh8ju58lE/bGb8k4227zbT3fyzro56lXa3OsU3NNlpThdITpsLX\n2zDU+k6EV3J8XZFi4+gqaQnZUuOcedejLYcX+ddL4QKBgQD4jd1CqlTpO5R7i8Rg\nGPzTKtgrCYcbm4G3FLymLaC5KELr1DF+MVOlF+lGswcKkaf1ZEU1Frux8Zt51M+r\nF0otmJr+NZwCXTXye0PIi/IDmDWqhXiv7BSnSEJ3jjqHWb/bMMRVt3hRaLFmjw/p\nH5u6APZHyQvZ7dGV0PdHiLMgFwKBgQDxAaYcXuy1vCgI+UxQvgWFibr0dYRWhB2U\nxRnPAUUj12npePEgt1f1AIoleI2Pr2U7bR+lU9tnNGB3B5beaX+5Gxao7KkNmuXk\nxbE7SXyegyiQzINIRBVb3B/0HGMVnu48kIvS2vyu3G04XQEwB1oIlW4MbFb8Fa03\nEOSCbkq5sQKBgQCTNnL2KSxhd4haJE4LHMGh0J533wzGrTQG26FgS2YGRHJeey9V\nLqH8Bk2EMkTZXau9C8ZxyyUgH5mWbxUQoJquptQl/FqKi+qH07ox7bFJr70ZYjQ4\n/fq9mW7EoNjJkb6wdBHVMvVwQjHQLKufx7jUUf2MRudeDB02Pq43ECAHwQKBgGpW\n9OltxPpHRE75WQADaEJMzE4TEEpwTvEWqtWY1N4ErXnT4Gk0HL5A97Oi5qtwk7VN\n5/m174gxJyM+GQaX/EA7wJrWmZ0kLK3twM7NFQyICL0jUAXx7I60qPC4GcwvbSUS\nDnACKh4pqpOFDgIYLFS/Qmh+4T6nfd9fN8SJT7VxAoGBAKJy5gT7xa6SseckE4aS\nSU8lIWOSum2gV1hPJYoMsQIhuXOmfTWa6u1gS8j1vw41BPFJJyI1UnbbEqWMLJqD\nRBTXFpyvY4sRY9dMkM1/Xij7UeNgXZ3muMUbFHkFTe1uHn3V8lY+RdZwMadvHWkb\nUIsQ+erbdXrDmHjkwCrrTEiY\n-----END PRIVATE KEY-----\n"""
  client_email="firebase-adminsdk-fbsvc@ai-tax-advisor-70984.iam.gserviceaccount.com"
  client_id="116423406325976565551"
  auth_uri="https://accounts.google.com/o/oauth2/auth"
  token_uri"="https://oauth2.googleapis.com/token"
  auth_provider_x509_cert_url="https://www.googleapis.com/oauth2/v1/certs"
  client_x509_cert_url="https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40ai-tax-advisor-70984.iam.gserviceaccount.com"
  universe_domain="googleapis.com"


